#!/usr/bin/env sh

# IMPORTANT: Lisez les instructions ci-dessous avant de faire quoi que ce soit!

echo ""
echo "🎯 INSTRUCTIONS DE DÉPLOIEMENT POUR RENDER.COM (GRATUIT)"
echo "========================================================"
echo ""
echo "ÉTAPE 1: Créer un compte Render"
echo "  1. Allez sur https://render.com"
echo "  2. Cliquez sur 'Sign Up'"
echo "  3. Connectez-vous avec GitHub ou créez un compte"
echo ""
echo "ÉTAPE 2: Créer un nouveau Web Service"
echo "  1. Dans le dashboard Render, cliquez sur 'New +'"
echo "  2. Sélectionnez 'Web Service'"
echo "  3. Connectez votre dépôt GitHub"
echo ""
echo "ÉTAPE 3: Configurer le déploiement"
echo "  - Nom: optimisation-differentiable"
echo "  - Langage: Python 3.11"
echo ""
echo "ÉTAPE 4: Définir les commandes"
echo "  Build Command:"
echo "    pip install -r backend/requirements.txt"
echo "  Start Command:"
echo "    cd backend && uvicorn main:app --host 0.0.0.0 --port \$PORT"
echo ""
echo "ÉTAPE 5: Variables d'environnement (optionnel)"
echo "  Aucune requise pour cette application"
echo ""
echo "ÉTAPE 6: Déployer"
echo "  Cliquez sur 'Create Web Service'"
echo "  Attendez que la construction se termine (2-3 minutes)"
echo ""
echo "ÉTAPE 7: Copier l'URL"
echo "  Une fois déployé, vous verrez une URL comme:"
echo "  https://optimisation-differentiable.onrender.com"
echo ""
echo "  Copiez cette URL et mettez-la à jour dans:"
echo "  frontend/lib/main.dart"
echo "  Ligne: ApiService.init('https://optimisation-differentiable.onrender.com');"
echo ""
echo "ÉTAPE 8: Rebuild et distribution"
echo "  ./setup.sh"
echo "  Choisir l'option 3 (Build APK)"
echo ""
echo "======================================================"
echo "✅ Votre app est prête à être distribuée!"
echo "======================================================"
echo ""
